### ISSUE TITLE
大佬，来看看电子科技大学这个加密怎么处理

### ISSUE THREAD

**Issue by ZimoLoveShuang** [LoseNine/Crack-JS-Spider#2]
https://idas.uestc.edu.cn/authserver/login?service=http%3A%2F%2Feportal.uestc.edu.cn%2Flogin%3Fservice%3Dhttp%3A%2F%2Feportal.uestc.edu.cn%2Fnew%2Findex.html

**Comment by LoseNine** [comment]
好，有时间解决一下，是个混淆

**Comment by ZimoLoveShuang** [comment]
对的，js混淆，辛苦大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LoseNine"<notifications@github.com&gt;; 
发送时间: 2020年5月27日(星期三) 晚上10:24
收件人: "LoseNine/Crack-JS-Spider"<Crack-JS-Spider@noreply.github.com&gt;; 
抄送: "子墨"<461009747@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [LoseNine/Crack-JS-Spider] 大佬，来看看电子科技大学这个加密怎么处理 (#2)





 
好，有时间解决一下，是个混淆
